<?php
/**
 *
 *  Copyright since 2011 Matthias Balke (magento@balke-technologies.de)
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
?><textarea id="<?php echo $this->getHtmlId() ?>" name="<?php echo $this->getName() ?>" <?php echo $this->serialize($this->getHtmlAttributes()) ?>><?php echo $this->getEscapedValue() ?></textarea><br />
<button class="scalable" type="button" id="balketechnologies_storemaintenance_add_my_ip">
    <span><?php echo $this->escapeHtml($this->getButtonLabel()); ?></span>
</button>

<script type="text/javascript">
    $('balketechnologies_storemaintenance_add_my_ip').observe('click', function() {
        ip = '<?php echo $_SERVER['REMOTE_ADDR'] ?>';
        
        allowedIps = $('<?php echo $this->getHtmlId(); ?>').innerHTML;
        
        delimiter = '';
        if (allowedIps != ''){
            delimiter = ', '
        }
        $('<?php echo $this->getHtmlId(); ?>').update( allowedIps + delimiter + ip);
    });
</script>